/**
 * Travel trivia — used by the labor-illusion loading screen (P3) and the
 * PDF "Did you know?" callouts (P8).
 *
 * Locale-keyed: each entry is translated for en/ko/ja/zh/fr so the
 * trivia matches the user's selected language. Falls back to the
 * locale's GENERIC pool when no country-specific data exists, then to
 * English-generic if the locale itself isn't supported.
 *
 * Slug format: lowercase, hyphenated, matched via COUNTRY_ALIASES.
 */

import type { Locale } from "../../i18n/locales";

type Pool = Record<string, string[]>;

const TRIVIA_EN: Pool = {
  japan: [
    "Japan has more vending machines per capita than any country on Earth — about one for every 23 people.",
    "Tokyo's Shinjuku Station handles 3.6 million passengers per day, more than any station in the world.",
    "There are over 200 official ramen styles in Japan, each tied to a specific city or region.",
    "Japanese taxi doors open and close automatically — never grab the handle yourself.",
    "Japan has 6,852 islands, but only 430 are inhabited.",
    "The Japanese word 'forest bathing' (shinrin-yoku) is now a recognized form of preventive health care.",
    "There's an island in Japan (Aoshima) where cats outnumber humans 100 to 1.",
    "Nara's deer bow back when you bow to them — they've learned it from generations of tourists.",
    "Mount Fuji is climbable only for two months a year (July and August).",
    "Japan recycles about 84% of its aluminum cans — the highest rate in the world.",
  ],
  france: [
    "France is the most-visited country in the world, with about 90 million tourists per year.",
    "There are 1,200 different types of cheese made in France.",
    "The Louvre is the world's largest art museum — it would take 100 days to see every piece for 30 seconds.",
    "Paris has only one stop sign in the entire city. The rule is: priority to the right.",
    "France's TGV trains can run at over 320 km/h on regular service.",
    "The Eiffel Tower grows about 15 cm taller in summer due to thermal expansion.",
    "France produces over 1,500 different wines, more than any other country.",
    "The French eat about 30,000 tons of snails per year.",
    "Carcassonne, in southern France, is the inspiration for Disney's Sleeping Beauty Castle.",
    "France has the highest railway network density in Europe — almost every village has a station.",
  ],
  thailand: [
    "Thailand is the only Southeast Asian country never colonized by a European power.",
    "Bangkok's full ceremonial name is 169 letters long — the longest city name in the world.",
    "Thailand has over 35,000 Buddhist temples (wats).",
    "The Thai greeting 'wai' (palms together) has different heights depending on the recipient's seniority.",
    "Bangkok's Chinatown is one of the oldest and largest outside China itself.",
    "Thai food was named the world's favorite cuisine in a 2019 CNN poll.",
    "Thailand exports more rice than any other country — about 25% of global trade.",
    "The Phi Phi Islands were closed in 2018 to let coral recover from over-tourism.",
    "Thailand has 1,430 islands, most of them uninhabited.",
    "The Thai word for elephant, 'chang', is also the name of the country's most popular beer.",
  ],
  "south-korea": [
    "South Korea has the fastest average internet speed in the world.",
    "Seoul is one of the world's largest metropolitan areas, with 25 million people in the greater region.",
    "The Korean alphabet, Hangul, was invented in 1443 and is considered one of the most logical writing systems ever created.",
    "Korean BBQ restaurants traditionally have ventilation hoods built into every table.",
    "South Korea has 22 national parks covering 6.7% of the country.",
    "The DMZ between North and South Korea is the most heavily guarded border on Earth — yet it's an accidental wildlife sanctuary.",
    "Koreans eat more instant ramen per capita than anyone else (~75 packets per person per year).",
    "South Korea's high-speed KTX train connects Seoul to Busan in 2 hours and 15 minutes.",
    "Kimchi has 187 official varieties, recognized by UNESCO as cultural heritage.",
    "Seoul has more coffee shops per capita than New York or Tokyo.",
  ],
  "united-states": [
    "The US has the most national parks in the world — 63 in total.",
    "Alaska is bigger than Texas, California, and Montana combined.",
    "There are more public libraries in the US than McDonald's locations.",
    "Times Square in New York gets over 50 million visitors per year — more than the Eiffel Tower.",
    "The Library of Congress holds over 170 million items, making it the largest library in the world.",
    "California alone is the world's 5th-largest economy.",
    "The US Interstate Highway System is over 77,000 km long.",
    "Yellowstone was the world's first national park, established in 1872.",
    "The Smithsonian has 19 museums in Washington DC — all free to enter.",
  ],
  italy: [
    "Italy has more UNESCO World Heritage sites than any other country.",
    "Rome's Trevi Fountain collects about €3,000 in coins every day, donated to charity.",
    "Italy has more pasta shapes than any country — over 350 documented varieties.",
    "Venice is built on 118 small islands connected by 400 bridges.",
    "The Vatican is the world's smallest country, at 0.49 km².",
    "Italy produces about 600 million liters of olive oil per year — the world's second-largest producer.",
    "Florence's Duomo took 142 years to build.",
    "Italians invented eyeglasses in the 13th century.",
    "Pizza Margherita was created in 1889 to honor Queen Margherita — its colors match the Italian flag.",
  ],
  spain: [
    "Spain has the second-highest number of UNESCO World Heritage sites in the world (after Italy).",
    "Spaniards eat dinner around 9-10pm — among the latest in Europe.",
    "Spain has 8,000 km of coastline.",
    "La Sagrada Familia in Barcelona has been under construction since 1882 and isn't finished yet.",
    "Flamenco was added to UNESCO's intangible cultural heritage list in 2010.",
    "Spain produces about 50% of the world's olive oil.",
    "The Spanish language is the world's second most-spoken native language.",
    "Tomatoes, potatoes, and chocolate were brought to Europe through Spain.",
  ],
  "united-kingdom": [
    "The UK has more castles per square mile than any other country.",
    "The London Underground (the Tube) is the world's oldest underground railway, opened in 1863.",
    "Big Ben is technically the bell, not the tower (which is now called Elizabeth Tower).",
    "There are over 30,000 pubs in the UK.",
    "Cheddar cheese originated in the village of Cheddar, England, around the 12th century.",
    "The British Library holds over 170 million items and adds about 3 million new ones per year.",
    "Stonehenge predates the Egyptian pyramids by about 500 years.",
    "Britain invented the modern postal service, the postage stamp, and the post box (1840s).",
  ],
  germany: [
    "Germany has over 1,500 different beer brands.",
    "There are 25,000 castles in Germany.",
    "German is the most widely spoken native language in Europe.",
    "Berlin has more bridges than Venice (over 1,700).",
    "Germany invented the printing press, the car, the MP3 format, and aspirin.",
    "Octoberfest actually starts in mid-September.",
    "Germany has more zoos than any country in Europe (over 400).",
    "Munich's Hofbräuhaus opened in 1589 and still serves beer today.",
  ],
  vietnam: [
    "Vietnam is the world's second-largest exporter of coffee.",
    "Hanoi's Old Quarter is over 1,000 years old.",
    "Ha Long Bay has nearly 2,000 limestone islands and islets.",
    "Vietnam has the longest cave in the world (Son Doong) — large enough to hold a 40-story skyscraper.",
    "Pho was originally a breakfast food in northern Vietnam.",
    "Vietnam grows about 90% of the world's cashew nuts.",
    "There are over 50 million motorbikes in Vietnam — almost one per two people.",
  ],
  indonesia: [
    "Indonesia is the world's largest archipelago — 17,508 islands, of which only about 6,000 are named.",
    "Bali alone has over 20,000 Hindu temples, more than anywhere else in Indonesia.",
    "Indonesians traditionally eat with the right hand only — the left is considered unclean.",
    "Bali's Mount Agung is the island's holiest spot; every Balinese home is built facing it.",
    "Indonesia is home to the Komodo dragon, the world's largest lizard at up to 3 meters long.",
    "Coffee in Bali is often served with the grounds still in the cup ('kopi tubruk') — let it settle, then sip from the top.",
    "The Indonesian word 'amok' (running amok) entered English from Malay-Indonesian.",
    "Bali has up to 5 rice harvest seasons per year thanks to the equatorial climate.",
    "Indonesia's national motto is 'Bhinneka Tunggal Ika' — Unity in Diversity. The country has over 700 living languages.",
    "The Borobudur temple in Java is the largest Buddhist monument in the world, predating Cambodia's Angkor Wat by 300 years.",
  ],
  iceland: [
    "Iceland has no surnames — Icelanders use patronymic last names (e.g., Magnúsdóttir = Magnús's daughter).",
    "Reykjavik is the world's northernmost capital, just 240 km south of the Arctic Circle.",
    "Iceland is the world's largest per-capita reader of books — about 1 in 10 Icelanders publishes a book in their lifetime.",
    "There are no mosquitoes in Iceland — they can't survive the climate.",
    "The Blue Lagoon's milky water is naturally heated geothermal seawater, around 38°C year-round.",
    "Iceland's police don't carry guns, and the country's national prison houses fewer than 200 inmates.",
    "Reykjavik runs almost entirely on renewable energy — geothermal heat warms most of the city's homes.",
    "The midnight sun never sets in late June; the polar night barely rises in late December.",
    "Iceland has a phone app to check whether your date is a relative — the population is just 380,000.",
    "Þingvellir National Park is the only place on Earth where you can walk between two tectonic plates above water.",
  ],
  peru: [
    "Cusco sits at 3,400 m above sea level — most travelers feel the altitude on day one. Coca-leaf tea (mate de coca) is the local fix.",
    "Machu Picchu was built without mortar; the stones fit so tightly you can't slide a credit card between them.",
    "Peru has over 4,000 varieties of native potato — more than anywhere else on Earth.",
    "Quechua, the language of the Inca, is still spoken by about 8 million people across the Andes.",
    "Lima gets less than 13 mm of rain per year — the world's second-driest capital, despite sitting on the coast.",
    "Peruvian ceviche is usually served with sweet potato and toasted corn (cancha) — the contrast cuts the lime.",
    "Cusco's Plaza de Armas was the political center of the entire Inca empire, then rebuilt by the Spanish on the same foundations.",
    "Pisco sour, Peru's national cocktail, must be served with a thick foamy egg-white head — that's the test of a real one.",
    "The Sacred Valley's terrace farming creates microclimates so dense one terrace can grow corn while the next grows tropical fruit.",
    "Peru is home to the Nazca Lines — geoglyphs 2,000 years old, only fully visible from the air.",
  ],
  "united-arab-emirates": [
    "The Burj Khalifa is so tall you can watch the sunset twice — once from ground level, then again from the 124th floor.",
    "The UAE has zero income tax — that's a big reason 88% of the population is foreign-born.",
    "Dubai's police fleet includes Lamborghinis, Ferraris, and a Bugatti Veyron — all real working patrol cars.",
    "Public displays of affection are technically illegal in the UAE; even married couples should keep hand-holding casual.",
    "Dubai gets just 100 mm of rain per year — when it rains, schools close because streets flood.",
    "The Palm Jumeirah is visible from space and is entirely man-made from dredged Gulf sand.",
    "Dubai Mall is the world's largest by total area — it contains an aquarium with 33,000 sea creatures.",
    "Camel milk chocolate is a real Dubai souvenir — sweeter than cow's milk and entirely halal-certified.",
    "Ramadan changes the city's rhythm: most restaurants don't serve until sunset, but tourist hotels often have screened daytime dining.",
    "Abu Dhabi's Sheikh Zayed Grand Mosque holds the world's largest hand-knotted carpet, woven by 1,300 weavers over two years.",
  ],
  taiwan: [
    "Taipei's night markets stay open until 1-2 AM — Shilin is the most famous, with over 500 stalls.",
    "Bubble tea (boba) was invented in Taiwan in the 1980s. Chun Shui Tang in Taichung claims the original, and they still serve it.",
    "Taipei 101 was the world's tallest building from 2004 to 2010. Inside is a 660-ton tuned mass damper visible to the public.",
    "Taiwan is shaped like a sweet potato — locals affectionately call themselves 'sweet potatoes' too.",
    "The Taipei MRT is famously clean — eating, drinking, and even chewing gum are banned with fines.",
    "7-Eleven in Taiwan does everything: bill payments, ticket pickup, dry cleaning, even sending wedding gifts.",
    "Stinky tofu smells alarming but tastes mild and crispy — try the Shenkeng version near Taipei, the original.",
    "Taiwan uses traditional Chinese characters (繁體字), unlike the simplified set used on the mainland.",
    "Beitou's hot springs, a 30-minute metro ride from central Taipei, have been a Japanese-influenced ritual since the early 1900s.",
    "Taiwan has 286 mountains over 3,000 meters — more high peaks per square kilometer than almost anywhere on Earth.",
  ],
};

const TRIVIA_KO: Pool = {
  japan: [
    "일본은 1인당 자판기 수가 세계 1위 — 약 23명당 1대꼴이에요.",
    "도쿄 신주쿠역은 하루 360만 명이 이용하는, 세계에서 가장 붐비는 역이에요.",
    "일본에는 200가지 넘는 공식 라멘 스타일이 있고, 각각 도시·지역에 묶여 있어요.",
    "일본 택시 문은 자동으로 열리고 닫혀요 — 절대 손잡이를 직접 잡지 마세요.",
    "일본은 6,852개 섬이 있지만 사람이 사는 곳은 430곳뿐이에요.",
    "일본어 '신린요쿠(森林浴, 숲 목욕)'는 이제 정식 예방 의료법으로 인정받고 있어요.",
    "일본 아오시마에는 사람보다 고양이가 100배 많은 섬이 있어요.",
    "나라의 사슴은 인사하면 같이 인사해요 — 관광객들에게서 학습한 거예요.",
    "후지산은 1년에 단 두 달(7월~8월)만 등반 가능해요.",
    "일본의 알루미늄 캔 재활용률은 약 84% — 세계 최고 수준이에요.",
  ],
  france: [
    "프랑스는 세계에서 가장 많은 관광객이 찾는 나라 — 연 약 9,000만 명이에요.",
    "프랑스에서 만들어지는 치즈는 1,200종이 넘어요.",
    "루브르는 세계 최대 미술관 — 모든 작품을 30초씩 보려면 100일이 걸려요.",
    "파리 전체에 정지 표지판은 단 1개뿐. 원칙: 오른쪽 우선.",
    "프랑스 TGV는 일반 운행 시속 320km 이상이에요.",
    "에펠탑은 여름엔 열팽창으로 약 15cm 더 커져요.",
    "프랑스는 1,500종 이상의 와인을 만들어 — 세계 1위.",
    "프랑스인은 매년 약 3만 톤의 달팽이를 먹어요.",
    "남프랑스 카르카손은 디즈니 잠자는 숲속의 공주성의 모티브가 됐어요.",
    "프랑스는 유럽에서 철도 밀도가 가장 높아 — 거의 모든 마을에 역이 있어요.",
  ],
  thailand: [
    "태국은 동남아에서 유럽 식민지가 된 적 없는 유일한 나라예요.",
    "방콕의 정식 의례 명칭은 169글자 — 세계에서 가장 긴 도시 이름이에요.",
    "태국에는 35,000곳 넘는 불교 사원(왓)이 있어요.",
    "태국식 인사 '와이'(합장)는 상대 연장자 정도에 따라 손 높이가 달라요.",
    "방콕 차이나타운은 중국 외 가장 오래되고 큰 차이나타운 중 하나예요.",
    "태국 음식은 2019년 CNN 조사에서 세계 1위 요리로 뽑혔어요.",
    "태국은 세계 최대 쌀 수출국 — 세계 무역량의 약 25%.",
    "피피 섬은 2018년 산호 회복을 위해 폐쇄됐어요.",
    "태국에는 1,430개의 섬이 있고, 대부분 무인도예요.",
    "태국어로 코끼리는 '창' — 태국 최고 인기 맥주 이름이기도 해요.",
  ],
  "south-korea": [
    "한국은 세계 평균 인터넷 속도 1위예요.",
    "서울은 광역 인구 2,500만 명, 세계 최대 대도시권 중 하나예요.",
    "한글은 1443년에 만들어졌고 가장 논리적인 문자 중 하나로 평가받아요.",
    "한국 고깃집은 테이블마다 환기 후드가 기본이에요.",
    "한국에는 22개 국립공원이 있고, 국토의 6.7%를 차지해요.",
    "남북 DMZ는 세계에서 가장 삼엄한 경계지만, 우연한 야생동물 보호구역이 됐어요.",
    "한국인의 1인당 라면 소비량은 세계 1위(연 약 75봉지).",
    "KTX는 서울-부산을 2시간 15분에 잇고 있어요.",
    "김치는 187가지 공식 종류가 있고, 유네스코 문화유산이에요.",
    "서울의 1인당 카페 수는 뉴욕·도쿄보다 많아요.",
  ],
  "united-states": [
    "미국은 세계에서 국립공원이 가장 많아 — 총 63곳.",
    "알래스카는 텍사스·캘리포니아·몬태나를 합친 것보다 커요.",
    "미국의 공공도서관 수는 맥도날드 매장 수보다 많아요.",
    "뉴욕 타임스스퀘어는 연 5,000만 명 이상 방문 — 에펠탑보다 많아요.",
    "미국 의회도서관은 1억 7천만 점 이상을 소장한 세계 최대 도서관이에요.",
    "캘리포니아 한 주만으로 세계 5위 경제 규모예요.",
    "미국 주간고속도로는 총연장 77,000km가 넘어요.",
    "옐로스톤은 1872년 지정된 세계 최초 국립공원이에요.",
    "워싱턴 DC 스미스소니언 19개 박물관은 전부 무료예요.",
  ],
  italy: [
    "이탈리아는 유네스코 세계유산이 가장 많은 나라예요.",
    "로마 트레비 분수는 매일 약 €3,000의 동전이 모여 자선단체에 기부돼요.",
    "이탈리아의 파스타 종류는 세계 1위 — 350가지 넘게 기록돼 있어요.",
    "베네치아는 118개 작은 섬이 400개 다리로 연결돼 있어요.",
    "바티칸은 면적 0.49km² — 세계에서 가장 작은 나라예요.",
    "이탈리아는 연간 약 6억 리터의 올리브유를 생산 — 세계 2위.",
    "피렌체 두오모를 짓는 데 142년이 걸렸어요.",
    "이탈리아인이 13세기에 안경을 발명했어요.",
    "마르게리타 피자는 1889년 마르게리타 여왕을 기리려 만들었고, 색깔은 이탈리아 국기와 같아요.",
  ],
  spain: [
    "스페인은 유네스코 세계유산이 두 번째로 많아요(이탈리아 다음).",
    "스페인 사람들은 보통 저녁 9-10시에 식사 — 유럽에서 가장 늦은 편이에요.",
    "스페인은 해안선이 8,000km나 돼요.",
    "바르셀로나 사그라다 파밀리아는 1882년 착공, 아직도 공사 중이에요.",
    "플라멩코는 2010년 유네스코 무형문화유산으로 등재됐어요.",
    "스페인은 세계 올리브유의 약 50%를 생산해요.",
    "스페인어는 세계에서 두 번째로 많이 쓰이는 모국어예요.",
    "토마토·감자·초콜릿이 스페인을 통해 유럽에 들어왔어요.",
  ],
  "united-kingdom": [
    "영국은 면적당 성 개수가 세계에서 가장 많아요.",
    "런던 지하철(튜브)은 1863년 개통 — 세계 최초의 지하철이에요.",
    "빅벤은 사실 종 이름 — 탑 자체는 엘리자베스 타워예요.",
    "영국에는 30,000곳이 넘는 펍이 있어요.",
    "체더 치즈는 12세기 영국 체더 마을에서 시작됐어요.",
    "영국 도서관은 1억 7천만 점 소장, 매년 300만 점이 추가돼요.",
    "스톤헨지는 이집트 피라미드보다 약 500년 더 오래됐어요.",
    "근대 우편 시스템·우표·우체통은 영국이 처음 만들었어요(1840년대).",
  ],
  germany: [
    "독일에는 1,500개 이상의 맥주 브랜드가 있어요.",
    "독일에는 25,000개의 성이 있어요.",
    "독일어는 유럽에서 가장 많이 쓰이는 모국어예요.",
    "베를린에는 다리가 1,700개 이상 — 베네치아보다 많아요.",
    "독일은 인쇄기·자동차·MP3·아스피린을 발명했어요.",
    "옥토버페스트는 사실 9월 중순에 시작해요.",
    "독일에는 유럽에서 가장 많은 동물원이 있어요(400곳 넘음).",
    "뮌헨 호프브로이하우스는 1589년 개업, 지금도 영업 중이에요.",
  ],
  vietnam: [
    "베트남은 세계 2위 커피 수출국이에요.",
    "하노이 구시가지는 1,000년이 넘었어요.",
    "할롱베이에는 약 2,000개의 석회암 섬이 있어요.",
    "베트남에는 세계에서 가장 긴 동굴 손둥(Son Doong) — 40층 빌딩이 들어갈 만큼 커요.",
    "쌀국수 '퍼'는 원래 베트남 북부의 아침 식사였어요.",
    "베트남은 세계 캐슈넛의 약 90%를 생산해요.",
    "베트남에는 5,000만 대 이상의 오토바이 — 인구 두 명당 한 대꼴이에요.",
  ],
  indonesia: [
    "인도네시아는 세계 최대 군도 — 17,508개 섬 중 이름이 있는 건 약 6,000개뿐이에요.",
    "발리 한 섬에만 힌두 사원이 2만 곳이 넘어요. 인도네시아 어느 섬보다 많아요.",
    "인도네시아에서는 전통적으로 오른손으로만 식사해요. 왼손은 부정한 손으로 여겨요.",
    "발리의 아궁 산은 섬에서 가장 신성한 곳 — 발리의 모든 집은 이 산을 향해 지어요.",
    "인도네시아에는 세계에서 가장 큰 도마뱀 코모도 드래곤이 살아요. 길이가 최대 3m나 돼요.",
    "발리에서는 커피를 가루째 부어 내는 'kopi tubruk' 스타일이 흔해요. 가라앉을 때까지 기다렸다가 위쪽만 마셔요.",
    "영어 단어 'amok'(아목, 광란)은 말레이-인도네시아어에서 왔어요.",
    "발리는 적도 기후 덕분에 한 해에 쌀을 5번까지 수확해요.",
    "인도네시아 국가 표어는 'Bhinneka Tunggal Ika' — '다양성 속의 통일'. 살아있는 언어가 700개가 넘어요.",
    "자바의 보로부두르 사원은 세계 최대 불교 유적 — 캄보디아 앙코르와트보다 300년 먼저 지었어요.",
  ],
  iceland: [
    "아이슬란드에는 성씨가 없어요. 부친의 이름에 -손/-도티르를 붙여요(예: Magnúsdóttir = 마그누스의 딸).",
    "레이캬비크는 세계에서 가장 북쪽에 있는 수도 — 북극권에서 240km밖에 안 떨어져 있어요.",
    "아이슬란드는 1인당 독서량 세계 1위 — 평생 책을 한 권 이상 출간하는 사람이 약 10명 중 1명이에요.",
    "아이슬란드에는 모기가 없어요. 기후가 모기에게 안 맞아요.",
    "블루 라군의 우윳빛 물은 자연 지열로 데워진 바닷물 — 1년 내내 약 38°C예요.",
    "아이슬란드 경찰은 총을 휴대하지 않고, 국가 교도소 수감자는 200명 미만이에요.",
    "레이캬비크는 거의 100% 재생에너지로 운영돼요 — 도시 대부분의 집은 지열로 난방해요.",
    "6월 말에는 해가 지지 않고, 12월 말에는 해가 거의 뜨지 않아요.",
    "인구 38만 명 — 데이트 상대가 친척인지 확인하는 앱이 실제로 있어요.",
    "싱벨리어 국립공원은 두 대륙판 사이를 지상에서 걸을 수 있는 지구상 유일한 곳이에요.",
  ],
  peru: [
    "쿠스코는 해발 3,400m — 첫날에 보통 고산증을 느껴요. 현지 해법은 코카잎 차(mate de coca)예요.",
    "마추픽추는 시멘트 없이 지었는데, 돌 사이에 신용카드 한 장도 안 들어갈 정도로 정교해요.",
    "페루에는 토종 감자 품종이 4,000가지가 넘어요. 세계 어느 곳보다 많아요.",
    "잉카 제국의 언어 케추아어는 안데스 전역에서 약 800만 명이 아직 써요.",
    "리마는 연간 강수량이 13mm도 안 돼요 — 해안 도시인데 세계에서 두 번째로 건조한 수도예요.",
    "페루의 세비체는 보통 고구마와 볶은 옥수수(cancha)와 함께 나와요. 라임의 신맛을 잡아줘요.",
    "쿠스코의 아르마스 광장은 잉카 제국의 정치 중심 — 스페인이 그 토대 위에 다시 지었어요.",
    "페루의 국민 칵테일 피스코 사워는 거품 머리가 두툼해야 진짜예요. 그게 시험대예요.",
    "성스러운 계곡의 계단식 농지는 미세기후가 너무 다양해서 한 단에서는 옥수수, 다음 단에서는 열대과일이 자라요.",
    "페루에는 2,000년 된 나스카 라인 지상화가 있어요. 공중에서만 전체 모양이 보여요.",
  ],
  "united-arab-emirates": [
    "부르즈 할리파는 너무 높아서 일몰을 두 번 볼 수 있어요 — 지상에서 한 번, 124층에서 또 한 번.",
    "UAE는 소득세가 없어요. 인구의 88%가 외국 출신인 큰 이유 중 하나예요.",
    "두바이 경찰차에는 람보르기니, 페라리, 부가티 베이론까지 있어요. 전부 실제 순찰차예요.",
    "UAE에서는 공공장소에서의 애정 표현이 법적으로 제한돼요. 부부 사이라도 손잡기 정도로만요.",
    "두바이는 연간 강수량이 100mm뿐이에요 — 비가 오면 도로가 잠겨서 학교가 휴교해요.",
    "팜 주메이라는 우주에서도 보이는 인공섬이에요. 걸프해의 모래를 끌어 올려 만들었어요.",
    "두바이 몰은 면적 기준 세계 최대 쇼핑몰 — 안에는 33,000마리가 사는 수족관이 있어요.",
    "낙타유 초콜릿은 두바이의 진짜 기념품이에요. 우유 초콜릿보다 단맛이 강하고 전부 할랄 인증이에요.",
    "라마단 기간에는 도시 리듬이 바뀌어요. 대부분 식당이 일몰 전에 영업하지 않지만, 관광객용 호텔은 가림막 안에서 낮에도 식사 가능해요.",
    "아부다비의 셰이크 자이드 그랜드 모스크에는 세계 최대 수직 카펫이 있어요. 1,300명이 2년에 걸쳐 짠 거예요.",
  ],
  taiwan: [
    "타이베이의 야시장은 보통 새벽 1-2시까지 열려요. 시린 야시장이 가장 유명한데, 가게가 500곳이 넘어요.",
    "버블티(보바)는 1980년대 대만에서 발명됐어요. 타이중의 춘쉐이탕(春水堂)이 원조라고 주장하고, 지금도 영업 중이에요.",
    "타이베이 101은 2004-2010년 세계 최고층 — 안에는 660톤짜리 동조질량댐퍼가 일반에 공개돼 있어요.",
    "대만은 모양이 고구마를 닮아서 현지인은 본인을 '고구마'라고도 불러요.",
    "타이베이 MRT는 청결로 유명해요. 식음료는 물론, 껌 씹기까지 벌금 부과해요.",
    "대만의 7-Eleven은 모든 걸 다 해요 — 공과금 결제, 티켓 픽업, 드라이클리닝, 결혼 선물 발송까지.",
    "취두부는 냄새가 강해서 놀라지만, 맛은 의외로 부드럽고 바삭해요. 타이베이 근교 선컹(深坑)이 원조라 가볼 만해요.",
    "대만은 번체자(繁體字)를 써요. 본토의 간체자와 달라요.",
    "타이베이 도심에서 지하철로 30분 거리의 베이터우 온천은 1900년대 일본 영향으로 시작된 의식이에요.",
    "대만에는 해발 3,000m가 넘는 산이 286개 — 면적당 고산이 세계에서 손꼽히게 많아요.",
  ],
};

const TRIVIA_JA: Pool = {
  japan: [
    "日本の自動販売機は人口比で世界一 — 約23人に1台あります。",
    "東京の新宿駅は1日360万人が利用 — 世界一の利用客数です。",
    "日本には200種類以上の公式ラーメンスタイルがあり、それぞれ都市・地域と結びついています。",
    "日本のタクシードアは自動で開閉 — 自分でハンドルを掴まないでください。",
    "日本には6,852の島があるが、人が住んでいるのは430のみです。",
    "「森林浴」は今や予防医学として正式に認められています。",
    "青島(あおしま)では猫が人間より100倍多く暮らしています。",
    "奈良の鹿は人間がお辞儀するとお辞儀を返します — 観光客から学んだものです。",
    "富士山は7・8月のたった2か月だけ登山できます。",
    "日本のアルミ缶リサイクル率は約84% — 世界最高水準です。",
  ],
  france: [
    "フランスは世界で最も観光客が訪れる国 — 年間約9,000万人。",
    "フランスのチーズは1,200種類以上あります。",
    "ルーブル美術館は世界最大 — 全作品を30秒ずつ見ても100日かかります。",
    "パリ市内全体に止まれの標識はたった1つ。原則は「右側優先」。",
    "TGVは通常運行で時速320km以上で走ります。",
    "エッフェル塔は夏に熱膨張で約15cm高くなります。",
    "フランスは1,500種以上のワインを生産 — 世界一です。",
    "フランス人は年間約3万トンのカタツムリを食べます。",
    "南仏カルカッソンヌはディズニー眠れる森の美女のお城のモデルです。",
    "フランスは欧州で最も鉄道網が密集 — ほぼ全ての村に駅があります。",
  ],
  thailand: [
    "タイは東南アジアで唯一、欧州列強に植民地化されなかった国です。",
    "バンコクの正式儀礼名は169文字 — 世界一長い都市名です。",
    "タイには35,000以上の仏教寺院(ワット)があります。",
    "タイの挨拶「ワイ」は相手の目上度合いで手の高さが変わります。",
    "バンコクのチャイナタウンは中国国外で最古・最大級の一つです。",
    "タイ料理は2019年CNN調査で世界一の料理に選ばれました。",
    "タイは世界最大の米輸出国 — 世界貿易の約25%を占めます。",
    "ピピ島は2018年、サンゴ回復のため閉鎖されました。",
    "タイには1,430の島があり、ほとんどが無人島です。",
    "タイ語で象は「チャーン」 — タイで一番人気のビールの名前でもあります。",
  ],
  "south-korea": [
    "韓国は平均インターネット速度が世界一です。",
    "ソウル都市圏の人口は2,500万人 — 世界最大級の都市圏です。",
    "ハングルは1443年に作られ、最も論理的な文字体系の一つとされています。",
    "韓国の焼肉店は各テーブルに換気フードが備わっています。",
    "韓国には22の国立公園があり、国土の6.7%を占めます。",
    "南北DMZは世界で最も警備が厳重な境界 — でも野生動物の楽園にもなっています。",
    "韓国人の1人当たりインスタントラーメン消費量は世界一(年間約75袋)。",
    "KTXはソウル~釜山を2時間15分で結びます。",
    "キムチには公式187種類があり、ユネスコ無形文化遺産です。",
    "ソウルの人口当たりカフェ数はニューヨークや東京より多いです。",
  ],
  "united-states": [
    "アメリカは国立公園数が世界一 — 計63か所。",
    "アラスカはテキサス・カリフォルニア・モンタナを合わせたより広いです。",
    "アメリカの公共図書館の数はマクドナルドの店舗数より多いです。",
    "ニューヨークのタイムズスクエアは年間5,000万人以上が訪問 — エッフェル塔より多いです。",
    "米国議会図書館は1億7,000万点以上を所蔵する世界最大の図書館です。",
    "カリフォルニア州だけで世界5位の経済規模です。",
    "アメリカの州間高速道路の総延長は77,000kmを超えます。",
    "イエローストーンは1872年指定の世界初の国立公園です。",
    "ワシントンDCのスミソニアン19博物館はすべて無料で入れます。",
  ],
  italy: [
    "イタリアはユネスコ世界遺産が世界一多い国です。",
    "ローマのトレビの泉には毎日約€3,000のコインが集まり、慈善団体に寄付されます。",
    "イタリアのパスタの種類は世界一 — 350種類以上が記録されています。",
    "ヴェネツィアは118の小島が400の橋で結ばれています。",
    "バチカンは0.49km² — 世界で最も小さな国です。",
    "イタリアは年間約6億リットルのオリーブオイルを生産 — 世界2位。",
    "フィレンツェのドゥオーモは142年かけて建てられました。",
    "13世紀にイタリア人がメガネを発明しました。",
    "マルゲリータピザは1889年マルゲリータ女王のために作られ、色はイタリア国旗と同じです。",
  ],
  spain: [
    "スペインはユネスコ世界遺産が世界2位(イタリアに次ぐ)。",
    "スペインの夕食は通常21~22時 — ヨーロッパで最も遅い部類です。",
    "スペインの海岸線は8,000kmあります。",
    "バルセロナのサグラダ・ファミリアは1882年着工、いまだ未完成です。",
    "フラメンコは2010年にユネスコ無形文化遺産に登録されました。",
    "スペインは世界のオリーブオイルの約50%を生産しています。",
    "スペイン語は世界で2番目に母語話者が多い言語です。",
    "トマト・ジャガイモ・チョコレートはスペイン経由でヨーロッパに伝わりました。",
  ],
  "united-kingdom": [
    "イギリスは面積あたりの城の数が世界一です。",
    "ロンドン地下鉄(チューブ)は1863年開業 — 世界最古の地下鉄です。",
    "ビッグベンは実は鐘の名前 — 塔自体はエリザベス・タワーです。",
    "イギリスには30,000以上のパブがあります。",
    "チェダーチーズは12世紀にイギリスのチェダー村で生まれました。",
    "大英図書館は1億7,000万点以上を所蔵し、年間300万点ずつ増えています。",
    "ストーンヘンジはエジプトのピラミッドより約500年古いです。",
    "近代郵便制度・切手・郵便ポストはイギリスが発明しました(1840年代)。",
  ],
  germany: [
    "ドイツには1,500以上のビール銘柄があります。",
    "ドイツには25,000の城があります。",
    "ドイツ語はヨーロッパで最も母語話者が多い言語です。",
    "ベルリンの橋はヴェネツィアより多い1,700以上あります。",
    "ドイツは活版印刷・自動車・MP3・アスピリンを発明しました。",
    "オクトーバーフェストは実は9月中旬に始まります。",
    "ドイツには欧州一の動物園数(400以上)があります。",
    "ミュンヘンのホフブロイハウスは1589年開業、今もビールを提供しています。",
  ],
  vietnam: [
    "ベトナムは世界第2位のコーヒー輸出国です。",
    "ハノイの旧市街は1,000年以上の歴史があります。",
    "ハロン湾には約2,000の石灰岩の島があります。",
    "ベトナムには世界一長い洞窟ソンドンがあり、40階建てビルが入る大きさです。",
    "フォーは元々ベトナム北部の朝食でした。",
    "ベトナムは世界のカシューナッツの約90%を生産しています。",
    "ベトナムにはオートバイが5,000万台以上 — 2人に1台の割合です。",
  ],
  indonesia: [
    "インドネシアは世界最大の群島国家 — 17,508の島のうち、名前があるのは約6,000島だけです。",
    "バリ島だけでヒンドゥー寺院は2万を超え、インドネシアのどの島より多いです。",
    "インドネシアでは伝統的に右手だけで食事します。左手は不浄とされます。",
    "バリ島のアグン山は最も神聖な場所で、バリのすべての家は山に向かって建てられます。",
    "インドネシアには世界最大のトカゲ、コモドオオトカゲが生息 — 体長3mに達します。",
    "バリのコーヒーは粉ごと注ぐ「kopi tubruk」が一般的です。沈むまで待ち、上澄みだけ飲みます。",
    "英語の「amok」(アモック、狂乱)はマレー・インドネシア語が起源です。",
    "バリは赤道気候のおかげで年に最大5回の稲作が可能です。",
    "インドネシアの国是は「Bhinneka Tunggal Ika」 — 多様性の中の統一。生きた言語が700以上あります。",
    "ジャワのボロブドゥール寺院は世界最大の仏教遺跡で、カンボジアのアンコールワットより300年早く建てられました。",
  ],
  iceland: [
    "アイスランドには姓がありません。父称(例:Magnúsdóttir = マグヌスの娘)を使います。",
    "レイキャヴィクは世界最北の首都 — 北極圏まで240kmの距離です。",
    "アイスランドは1人あたりの読書量が世界一 — 生涯に本を出版する人の割合は約10人に1人です。",
    "アイスランドには蚊がいません。気候が合わないからです。",
    "ブルーラグーンの乳白色の水は、自然の地熱で温められた海水で、年中約38°Cです。",
    "アイスランドの警察は銃を携帯せず、国の刑務所には200人未満しか収監されていません。",
    "レイキャヴィクはほぼ100%再生可能エネルギーで運営され、家屋の暖房は地熱を使います。",
    "6月末は太陽が沈まず、12月末は太陽がほとんど昇りません。",
    "人口38万人 — デート相手が親戚かどうかを確認するアプリが実在します。",
    "シンクヴェトリル国立公園は、地上で2つの大陸プレートの間を歩ける地球上唯一の場所です。",
  ],
  peru: [
    "クスコは標高3,400m — 多くの旅行者が初日に高山病を感じます。地元の対処法はコカ茶(mate de coca)です。",
    "マチュピチュはモルタルなしで建てられ、石の隙間にクレジットカードも入らないほど精密です。",
    "ペルーには在来種のジャガイモが4,000種以上あり、世界最多です。",
    "インカの言語ケチュア語は、アンデス全域で今も約800万人が話しています。",
    "リマは年間降水量13mm未満 — 沿岸都市なのに世界第2位の乾燥した首都です。",
    "ペルーのセビーチェはサツマイモと炒りトウモロコシ(cancha)と一緒に出てきます。ライムの酸味を和らげます。",
    "クスコのアルマス広場はインカ帝国の政治の中心で、スペインがその基礎の上に再建しました。",
    "ペルーの国民的カクテル、ピスコサワーは厚い卵白の泡が決め手 — 本物かどうかの試金石です。",
    "聖なる谷の段々畑は微気候が密で、ある段ではトウモロコシ、隣の段では熱帯果実が育ちます。",
    "ペルーには2,000年前のナスカの地上絵があり、空からしか全体が見えません。",
  ],
  "united-arab-emirates": [
    "ブルジュ・ハリファは高すぎて夕日を2回見られます — 地上で1回、124階でもう1回。",
    "UAEは所得税ゼロ。人口の88%が外国出身である大きな理由です。",
    "ドバイ警察にはランボルギーニ、フェラーリ、ブガッティ・ヴェイロンも — すべて実働パトカーです。",
    "UAEでは公共の場での愛情表現は法的に制限されます。夫婦でも手を握る程度に留めるのが無難です。",
    "ドバイの年間降水量は100mmだけ — 雨が降ると道路が冠水して学校が休校になります。",
    "パーム・ジュメイラは宇宙からも見える人工島で、湾の砂を浚渫して造られました。",
    "ドバイモールは面積で世界最大 — 中には33,000匹の海洋生物がいる水族館があります。",
    "ラクダのミルクチョコレートは本物のドバイ土産で、牛乳より甘く、すべてハラル認証です。",
    "ラマダン中は街のリズムが変わります。多くのレストランは日没まで営業せず、観光客向けホテルは目隠し付きで日中も食事を提供します。",
    "アブダビのシェイク・ザイード・グランドモスクには世界最大の手織りカーペットがあり、1,300人が2年かけて織りました。",
  ],
  taiwan: [
    "台北の夜市は深夜1-2時まで開いていて、士林夜市は500軒以上の屋台がある最も有名な場所です。",
    "タピオカミルクティー(ボバ)は1980年代に台湾で生まれました。台中の春水堂が元祖を主張し、今も営業中です。",
    "台北101は2004-2010年に世界一高いビル — 660トンの制振機(チューンドマスダンパー)が一般公開されています。",
    "台湾の形はサツマイモ似で、台湾人は自分たちを「サツマイモ」と愛称で呼ぶこともあります。",
    "台北MRTは清潔さで有名 — 飲食はもちろん、ガムを噛むことまで罰金対象です。",
    "台湾のセブンイレブンは何でもできます — 公共料金支払い、チケット受取、クリーニング、結婚祝い発送まで。",
    "臭豆腐は匂いは強烈ですが、味はマイルドでサクサクしています。台北郊外の深坑が発祥で訪れる価値があります。",
    "台湾は繁体字(繁體字)を使い、本土の簡体字とは異なります。",
    "台北中心から地下鉄30分の北投温泉は、1900年代の日本統治時代から続く儀式です。",
    "台湾には標高3,000m超の山が286座あり、面積あたりの高山数は世界屈指です。",
  ],
};

const TRIVIA_ZH: Pool = {
  japan: [
    "日本人均自动售货机数量世界第一 — 约每23人就有一台。",
    "东京新宿站日均客流量360万人次,是世界上最繁忙的车站。",
    "日本有200多种官方拉面流派,各与特定城市或地区相关联。",
    "日本出租车的车门会自动开关 — 千万别自己拉门把手。",
    "日本有6,852个岛屿,但只有430个有人居住。",
    "日语「森林浴」(shinrin-yoku)如今被正式认定为预防医学方式。",
    "日本青岛(Aoshima)上猫的数量是人的100倍。",
    "奈良的鹿会向人鞠躬还礼 — 它们从一代代游客身上学会的。",
    "富士山每年仅7、8两个月可登山。",
    "日本铝罐回收率约84% — 世界最高。",
  ],
  france: [
    "法国是世界上游客最多的国家 — 每年约9,000万人。",
    "法国出产1,200种不同的奶酪。",
    "卢浮宫是世界最大的艺术博物馆 — 每件作品看30秒,需要100天才能看完。",
    "巴黎全市只有一个停车标志。规则是:右侧优先。",
    "法国TGV高速列车日常运营时速超过320公里。",
    "埃菲尔铁塔夏天因热膨胀会高出约15厘米。",
    "法国出产1,500多种葡萄酒,世界第一。",
    "法国人每年吃掉约3万吨蜗牛。",
    "法国南部卡尔卡松城是迪士尼睡美人城堡的灵感来源。",
    "法国是欧洲铁路网密度最高的国家 — 几乎每个村庄都有车站。",
  ],
  thailand: [
    "泰国是东南亚唯一从未被欧洲列强殖民的国家。",
    "曼谷的完整礼仪名长达169字母 — 世界最长的城市名。",
    "泰国有35,000多座佛教寺院(瓦特)。",
    "泰式问候「合十礼」(wai)的高度根据对方资历不同而不同。",
    "曼谷唐人街是中国境外最古老、最大的唐人街之一。",
    "泰国菜在2019年CNN评选中被誉为世界最受欢迎的菜系。",
    "泰国是全球最大稻米出口国 — 占全球贸易约25%。",
    "皮皮岛于2018年关闭,以让珊瑚从过度旅游中恢复。",
    "泰国有1,430个岛屿,大多数无人居住。",
    "泰语「象」叫「Chang」 — 也是泰国最受欢迎啤酒的名字。",
  ],
  "south-korea": [
    "韩国平均互联网速度全球第一。",
    "首尔是世界最大都会区之一,大都会人口约2,500万。",
    "韩文(Hangul)创制于1443年,被誉为世界上最具逻辑性的文字之一。",
    "韩式烤肉店每张桌子都内置抽风机。",
    "韩国有22个国家公园,占国土面积的6.7%。",
    "南北韩DMZ是世界上戒备最森严的边界 — 但意外地成了野生动物保护区。",
    "韩国人均方便面消费量世界第一(每年约75袋)。",
    "韩国KTX高速列车连接首尔到釜山仅需2小时15分钟。",
    "泡菜有187种官方品种,被联合国教科文组织列为文化遗产。",
    "首尔人均咖啡店数量超过纽约和东京。",
  ],
  "united-states": [
    "美国是世界上国家公园数量最多的国家 — 共63个。",
    "阿拉斯加比德州、加州和蒙大拿州加起来还大。",
    "美国公共图书馆数量比麦当劳门店还多。",
    "纽约时代广场每年游客超过5,000万 — 比埃菲尔铁塔还多。",
    "美国国会图书馆藏书超过1.7亿件,是世界最大图书馆。",
    "光加州一个州就是世界第5大经济体。",
    "美国州际公路系统总长超过77,000公里。",
    "黄石是世界上第一个国家公园,1872年设立。",
    "华盛顿特区的史密森尼学会有19个博物馆,全部免费入场。",
  ],
  italy: [
    "意大利是世界联合国教科文组织遗产最多的国家。",
    "罗马特雷维喷泉每天约收到€3,000的硬币,捐给慈善机构。",
    "意大利的意面种类世界第一 — 已记录的就超过350种。",
    "威尼斯由118个小岛组成,通过400座桥连接。",
    "梵蒂冈是世界最小的国家,面积仅0.49平方公里。",
    "意大利每年生产约6亿升橄榄油 — 世界第二大生产国。",
    "佛罗伦萨大教堂(Duomo)耗时142年才建成。",
    "意大利人在13世纪发明了眼镜。",
    "玛格丽特披萨创于1889年,为致敬玛格丽特女王 — 颜色对应意大利国旗。",
  ],
  spain: [
    "西班牙的联合国教科文组织世界遗产数量世界第二(仅次于意大利)。",
    "西班牙人通常晚上9-10点才吃晚饭 — 欧洲最晚的之一。",
    "西班牙的海岸线长达8,000公里。",
    "巴塞罗那的圣家堂自1882年开建,至今未完工。",
    "弗拉门戈舞2010年被列入联合国非物质文化遗产名录。",
    "西班牙生产全球约50%的橄榄油。",
    "西班牙语是世界上第二大母语使用者最多的语言。",
    "番茄、土豆、巧克力都是经由西班牙传入欧洲的。",
  ],
  "united-kingdom": [
    "英国每平方英里的城堡数量世界第一。",
    "伦敦地铁(Tube)1863年通车 — 世界上最古老的地铁。",
    "「大本钟」其实是钟的名字 — 钟楼现称伊丽莎白塔。",
    "英国有超过30,000家酒吧。",
    "切达奶酪起源于英国切达村,约12世纪。",
    "大英图书馆藏书1.7亿件,每年新增约300万件。",
    "巨石阵比埃及金字塔还早约500年。",
    "现代邮政、邮票、邮筒都是英国发明的(1840年代)。",
  ],
  germany: [
    "德国有超过1,500种啤酒品牌。",
    "德国有25,000座城堡。",
    "德语是欧洲母语使用者最多的语言。",
    "柏林的桥比威尼斯还多(超过1,700座)。",
    "德国发明了印刷机、汽车、MP3和阿司匹林。",
    "啤酒节其实是9月中旬开始的。",
    "德国是欧洲动物园数量最多的国家(超过400个)。",
    "慕尼黑皇家啤酒屋(Hofbräuhaus)1589年开业,至今仍在营业。",
  ],
  vietnam: [
    "越南是世界第二大咖啡出口国。",
    "河内老城区已有1,000多年历史。",
    "下龙湾有近2,000座石灰岩岛屿。",
    "越南有世界最长的洞穴山东(Son Doong) — 大到能容下40层楼的摩天大楼。",
    "越南河粉(Pho)最初是越南北部的早餐食物。",
    "越南生产全球约90%的腰果。",
    "越南有超过5,000万辆摩托车 — 几乎每两人就有一辆。",
  ],
  indonesia: [
    "印度尼西亚是世界最大的群岛国家 — 17,508个岛屿中只有约6,000个有名字。",
    "仅巴厘岛就有超过2万座印度教寺庙,比印尼任何岛屿都多。",
    "印度尼西亚人传统上只用右手吃饭,左手被视为不洁。",
    "巴厘岛的阿贡火山是岛上最神圣的地方,巴厘人的每一栋房子都朝向它而建。",
    "印度尼西亚是世界最大蜥蜴科莫多巨蜥的栖息地,体长可达3米。",
    "巴厘岛的咖啡常常带着粉一起冲(称为kopi tubruk),等粉沉淀后从上层啜饮。",
    "英文单词「amok」(发狂)源自马来-印度尼西亚语。",
    "巴厘岛因赤道气候,一年最多可收割5次稻谷。",
    "印度尼西亚的国家箴言是「Bhinneka Tunggal Ika」 — 多元一体,境内有700多种活语言。",
    "爪哇的婆罗浮屠是世界最大佛教遗迹,比柬埔寨的吴哥窟早300年建成。",
  ],
  iceland: [
    "冰岛人没有姓氏 — 使用父名加后缀(例:Magnúsdóttir = 马格努斯的女儿)。",
    "雷克雅未克是世界最北的首都,距北极圈仅240公里。",
    "冰岛人均阅读量世界第一 — 大约每10人中就有1人在一生中出版过书。",
    "冰岛没有蚊子,因为气候不适合它们生存。",
    "蓝湖乳白色的水是天然地热加热的海水,全年保持约38°C。",
    "冰岛警察不携带枪支,全国监狱关押人数不到200人。",
    "雷克雅未克几乎100%使用可再生能源 — 大多数家庭由地热供暖。",
    "六月底太阳不下山,十二月底太阳几乎不升起。",
    "冰岛人口仅38万 — 真的有一款手机应用可以查约会对象是不是亲戚。",
    "辛格维利尔国家公园是地球上唯一可以在地表上行走在两块大陆板块之间的地方。",
  ],
  peru: [
    "库斯科海拔3,400米 — 多数旅客第一天会感到高原反应,当地解法是古柯叶茶(mate de coca)。",
    "马丘比丘是不用灰浆建成的,石块之间紧到连一张信用卡都塞不进去。",
    "秘鲁有超过4,000种本地土豆,世界最多。",
    "印加帝国的语言克丘亚语,至今仍有约800万人在安第斯山区使用。",
    "利马年降雨量不到13毫米 — 沿海城市却是世界第二干燥的首都。",
    "秘鲁的酸橘汁腌鱼(ceviche)通常配甘薯和炒玉米(cancha)上桌,可以中和酸柠汁的酸味。",
    "库斯科的兵器广场曾是整个印加帝国的政治中心,西班牙人在原地基上重建了它。",
    "秘鲁国饮Pisco Sour必须有厚厚的蛋白泡沫顶 — 那是辨别真伪的标准。",
    "圣谷的梯田农耕造就了密集的微气候,一层种玉米,下一层就能种热带水果。",
    "秘鲁有2,000年前的纳斯卡线条地画 — 只有从空中才能看到全貌。",
  ],
  "united-arab-emirates": [
    "哈利法塔太高了,可以看两次日落 — 一次在地面,一次在124层。",
    "阿联酋没有所得税 — 这是88%人口为外国出生的重要原因。",
    "迪拜警察的车队包括兰博基尼、法拉利,甚至布加迪威龙 — 全是真正的巡逻车。",
    "在阿联酋,公开场合的亲密举动在法律上受限,夫妻也只宜轻牵手。",
    "迪拜年降雨量仅100毫米 — 一旦下雨,街道积水,学校就停课。",
    "棕榈岛(Palm Jumeirah)从太空也能看到,完全由疏浚海湾的沙子人工填造。",
    "迪拜购物中心(Dubai Mall)是世界面积最大的商场 — 内部水族馆有33,000只海洋生物。",
    "骆驼奶巧克力是迪拜的真正特产 — 比牛奶巧克力更甜,且全部清真认证。",
    "斋月期间城市节奏改变,大多数餐厅日落前不营业,但游客酒店常有遮挡的日间用餐区。",
    "阿布扎比的谢赫扎耶德大清真寺有世界最大的手工编织地毯,1,300名织工花了两年时间。",
  ],
  taiwan: [
    "台北的夜市通常营业到凌晨1-2点,士林夜市最有名,有500多个摊位。",
    "珍珠奶茶(波霸)1980年代发源于台湾。台中的春水堂自称原创,如今仍在营业。",
    "台北101曾是2004-2010年的世界第一高楼,内部有660吨重的调谐质量阻尼器对外公开。",
    "台湾形似番薯,本地人也亲切地自称「番薯仔」。",
    "台北捷运以洁净闻名 — 饮食、嚼口香糖都会被罚款。",
    "台湾的7-Eleven什么都能办 — 缴账单、取票、送干洗、甚至代寄结婚礼物。",
    "臭豆腐闻起来惊人,味道却出乎意料地温和酥脆。台北近郊的深坑是发源地,值得一访。",
    "台湾使用繁体字(繁體字),与大陆的简体字不同。",
    "从台北市中心搭捷运30分钟可达的北投温泉,自1900年代起延续日治时期的泡汤仪式。",
    "台湾有286座海拔3,000米以上的山,每平方公里的高山数量在世界上名列前茅。",
  ],
};

const TRIVIA_FR: Pool = {
  japan: [
    "Le Japon a le plus grand nombre de distributeurs automatiques par habitant — environ un pour 23 personnes.",
    "La gare de Shinjuku à Tokyo accueille 3,6 millions de passagers par jour, plus que toute autre gare au monde.",
    "Il existe plus de 200 styles officiels de ramen au Japon, chacun lié à une ville ou région spécifique.",
    "Les portes de taxi japonaises s'ouvrent et se ferment automatiquement — n'attrapez jamais la poignée.",
    "Le Japon compte 6 852 îles, mais seulement 430 sont habitées.",
    "Le terme japonais shinrin-yoku (« bain de forêt ») est désormais reconnu comme une forme de médecine préventive.",
    "Sur l'île japonaise d'Aoshima, les chats sont 100 fois plus nombreux que les humains.",
    "Les cerfs de Nara s'inclinent en retour quand vous les saluez — ils l'ont appris des touristes au fil des générations.",
    "Le mont Fuji n'est ouvert à l'ascension que deux mois par an (juillet et août).",
    "Le Japon recycle environ 84 % de ses canettes en aluminium — le taux le plus élevé au monde.",
  ],
  france: [
    "La France est le pays le plus visité au monde, avec environ 90 millions de touristes par an.",
    "On fabrique 1 200 types différents de fromage en France.",
    "Le Louvre est le plus grand musée d'art au monde — il faudrait 100 jours pour voir chaque œuvre 30 secondes.",
    "Paris ne compte qu'un seul stop dans toute la ville. La règle: priorité à droite.",
    "Les TGV roulent à plus de 320 km/h en service régulier.",
    "La tour Eiffel grandit d'environ 15 cm en été à cause de la dilatation thermique.",
    "La France produit plus de 1 500 vins différents — plus que n'importe quel autre pays.",
    "Les Français mangent environ 30 000 tonnes d'escargots par an.",
    "Carcassonne, dans le sud, a inspiré le château de la Belle au bois dormant de Disney.",
    "La France a la densité ferroviaire la plus élevée d'Europe — presque chaque village a une gare.",
  ],
  thailand: [
    "La Thaïlande est le seul pays d'Asie du Sud-Est jamais colonisé par une puissance européenne.",
    "Le nom cérémoniel complet de Bangkok fait 169 lettres — le plus long nom de ville au monde.",
    "La Thaïlande compte plus de 35 000 temples bouddhistes (wats).",
    "Le salut thaï « wai » (mains jointes) varie en hauteur selon l'ancienneté du destinataire.",
    "Le Chinatown de Bangkok est l'un des plus anciens et des plus grands hors de Chine.",
    "La cuisine thaïe a été élue cuisine préférée au monde par un sondage CNN en 2019.",
    "La Thaïlande exporte plus de riz que tout autre pays — environ 25 % du commerce mondial.",
    "Les îles Phi Phi ont été fermées en 2018 pour permettre aux coraux de se régénérer.",
    "La Thaïlande a 1 430 îles, dont la plupart sont inhabitées.",
    "Le mot thaï pour éléphant, « chang », est aussi le nom de la bière la plus populaire du pays.",
  ],
  "south-korea": [
    "La Corée du Sud a la connexion internet moyenne la plus rapide au monde.",
    "Séoul est l'une des plus grandes métropoles du monde, avec 25 millions d'habitants en agglomération.",
    "L'alphabet coréen, le hangul, a été inventé en 1443 et est considéré comme l'un des plus logiques jamais créés.",
    "Les restaurants de barbecue coréen ont traditionnellement des hottes intégrées à chaque table.",
    "La Corée du Sud compte 22 parcs nationaux qui couvrent 6,7 % du pays.",
    "La DMZ entre les deux Corées est la frontière la plus militarisée au monde — mais aussi un sanctuaire accidentel pour la faune.",
    "Les Coréens consomment plus de ramen instantanés par habitant que n'importe qui d'autre (~75 paquets par an).",
    "Le KTX relie Séoul à Busan en 2 h 15.",
    "Le kimchi compte 187 variétés officielles, reconnues par l'UNESCO comme patrimoine culturel.",
    "Séoul a plus de cafés par habitant que New York ou Tokyo.",
  ],
  "united-states": [
    "Les États-Unis ont le plus grand nombre de parcs nationaux au monde — 63 au total.",
    "L'Alaska est plus grand que le Texas, la Californie et le Montana réunis.",
    "Il y a plus de bibliothèques publiques aux États-Unis que de McDonald's.",
    "Times Square à New York reçoit plus de 50 millions de visiteurs par an — plus que la tour Eiffel.",
    "La Bibliothèque du Congrès détient plus de 170 millions d'objets — la plus grande bibliothèque au monde.",
    "À elle seule, la Californie est la 5e économie mondiale.",
    "Le réseau d'autoroutes inter-États fait plus de 77 000 km.",
    "Yellowstone fut le premier parc national au monde, créé en 1872.",
    "La Smithsonian compte 19 musées à Washington DC — tous gratuits.",
  ],
  italy: [
    "L'Italie a plus de sites du patrimoine mondial de l'UNESCO que n'importe quel autre pays.",
    "La fontaine de Trevi à Rome récolte environ 3 000 € de pièces par jour, reversés à des œuvres caritatives.",
    "L'Italie a plus de formes de pâtes que tout autre pays — plus de 350 documentées.",
    "Venise est bâtie sur 118 petites îles reliées par 400 ponts.",
    "Le Vatican est le plus petit pays du monde, avec 0,49 km².",
    "L'Italie produit environ 600 millions de litres d'huile d'olive par an — 2e producteur mondial.",
    "Le Duomo de Florence a pris 142 ans à construire.",
    "Les Italiens ont inventé les lunettes au 13e siècle.",
    "La pizza Margherita a été créée en 1889 pour honorer la reine Marguerite — ses couleurs reprennent le drapeau italien.",
  ],
  spain: [
    "L'Espagne a le 2e plus grand nombre de sites UNESCO au monde (après l'Italie).",
    "Les Espagnols dînent vers 21-22 h — parmi les plus tardifs d'Europe.",
    "L'Espagne a 8 000 km de côtes.",
    "La Sagrada Familia à Barcelone est en construction depuis 1882 et n'est toujours pas terminée.",
    "Le flamenco a été ajouté au patrimoine immatériel de l'UNESCO en 2010.",
    "L'Espagne produit environ 50 % de l'huile d'olive mondiale.",
    "L'espagnol est la 2e langue maternelle la plus parlée au monde.",
    "Les tomates, pommes de terre et chocolat ont été introduits en Europe via l'Espagne.",
  ],
  "united-kingdom": [
    "Le Royaume-Uni a la plus forte densité de châteaux au monde.",
    "Le métro de Londres (le Tube) est le plus ancien du monde, ouvert en 1863.",
    "Big Ben désigne en réalité la cloche, pas la tour (qu'on appelle désormais Elizabeth Tower).",
    "Le Royaume-Uni compte plus de 30 000 pubs.",
    "Le cheddar est né dans le village de Cheddar, en Angleterre, vers le 12e siècle.",
    "La British Library détient plus de 170 millions d'objets et en ajoute 3 millions par an.",
    "Stonehenge précède les pyramides d'Égypte d'environ 500 ans.",
    "La Grande-Bretagne a inventé la poste moderne, le timbre-poste et la boîte aux lettres (années 1840).",
  ],
  germany: [
    "L'Allemagne compte plus de 1 500 marques de bière différentes.",
    "Il y a 25 000 châteaux en Allemagne.",
    "L'allemand est la langue maternelle la plus parlée d'Europe.",
    "Berlin a plus de ponts que Venise (plus de 1 700).",
    "L'Allemagne a inventé l'imprimerie, l'automobile, le format MP3 et l'aspirine.",
    "L'Oktoberfest commence en réalité à la mi-septembre.",
    "L'Allemagne a le plus grand nombre de zoos d'Europe (plus de 400).",
    "La Hofbräuhaus de Munich a ouvert en 1589 et sert toujours de la bière aujourd'hui.",
  ],
  vietnam: [
    "Le Vietnam est le 2e exportateur mondial de café.",
    "Le vieux quartier de Hanoï a plus de 1 000 ans.",
    "La baie d'Halong compte près de 2 000 îles et îlots calcaires.",
    "Le Vietnam abrite la plus longue grotte du monde (Son Doong) — assez grande pour un gratte-ciel de 40 étages.",
    "Le pho était à l'origine un plat du petit-déjeuner du nord du Vietnam.",
    "Le Vietnam produit environ 90 % des noix de cajou mondiales.",
    "Il y a plus de 50 millions de motos au Vietnam — presque une pour deux personnes.",
  ],
  indonesia: [
    "L'Indonésie est le plus grand archipel du monde — 17 508 îles, dont seulement 6 000 environ ont un nom.",
    "Bali à elle seule compte plus de 20 000 temples hindous, plus que toute autre île d'Indonésie.",
    "Les Indonésiens mangent traditionnellement avec la main droite uniquement — la gauche est considérée comme impure.",
    "Le mont Agung de Bali est le lieu le plus sacré de l'île, et toutes les maisons balinaises sont orientées vers lui.",
    "L'Indonésie abrite le dragon de Komodo, le plus grand lézard du monde, jusqu'à 3 mètres de long.",
    "À Bali, le café est souvent servi avec le marc encore dedans (le « kopi tubruk ») — laissez décanter, puis sirotez le dessus.",
    "Le mot anglais « amok » (devenir fou furieux) vient du malais-indonésien.",
    "Bali récolte le riz jusqu'à 5 fois par an grâce au climat équatorial.",
    "La devise nationale est « Bhinneka Tunggal Ika » — Unité dans la diversité. Le pays compte plus de 700 langues vivantes.",
    "Le temple de Borobudur à Java est le plus grand monument bouddhiste au monde et précède Angkor Vat de 300 ans.",
  ],
  iceland: [
    "L'Islande n'a pas de noms de famille — les Islandais utilisent un patronyme (ex. Magnúsdóttir = fille de Magnús).",
    "Reykjavik est la capitale la plus septentrionale au monde, à seulement 240 km au sud du cercle arctique.",
    "L'Islande détient le record de lecture par habitant — environ 1 Islandais sur 10 publie un livre dans sa vie.",
    "Il n'y a pas de moustiques en Islande — le climat ne leur convient pas.",
    "L'eau laiteuse du Blue Lagoon est de l'eau de mer naturellement chauffée par géothermie, à environ 38 °C toute l'année.",
    "La police islandaise ne porte pas d'arme, et la prison nationale héberge moins de 200 détenus.",
    "Reykjavik fonctionne presque entièrement aux énergies renouvelables — la géothermie chauffe la plupart des foyers.",
    "Le soleil ne se couche jamais fin juin ; la nuit polaire à peine ne se lève fin décembre.",
    "Avec seulement 380 000 habitants, une application téléphone existe vraiment pour vérifier si votre rencard est un parent.",
    "Le parc national de Þingvellir est le seul endroit sur Terre où l'on peut marcher entre deux plaques tectoniques à l'air libre.",
  ],
  peru: [
    "Cuzco est à 3 400 m d'altitude — la plupart des voyageurs ressentent le mal d'altitude le premier jour. Le remède local : la tisane de coca (mate de coca).",
    "Le Machu Picchu a été construit sans mortier ; les pierres s'imbriquent si parfaitement qu'on ne peut pas glisser une carte de crédit entre elles.",
    "Le Pérou compte plus de 4 000 variétés de pommes de terre indigènes — un record mondial.",
    "Le quechua, langue de l'Inca, est encore parlé par environ 8 millions de personnes dans les Andes.",
    "Lima reçoit moins de 13 mm de pluie par an — c'est la deuxième capitale la plus sèche au monde, malgré sa façade côtière.",
    "Le ceviche péruvien est servi avec de la patate douce et du maïs grillé (cancha) — le contraste adoucit l'acidité du citron vert.",
    "La Plaza de Armas de Cuzco fut le centre politique de tout l'empire inca, puis reconstruite par les Espagnols sur les mêmes fondations.",
    "Le Pisco Sour, cocktail national du Pérou, doit avoir une mousse de blanc d'œuf bien épaisse — c'est le test du vrai.",
    "L'agriculture en terrasses de la Vallée Sacrée crée des microclimats si denses qu'une terrasse fait pousser du maïs et la suivante des fruits tropicaux.",
    "Le Pérou abrite les lignes de Nazca, géoglyphes vieux de 2 000 ans, visibles uniquement depuis les airs.",
  ],
  "united-arab-emirates": [
    "Le Burj Khalifa est si haut que vous pouvez voir le coucher de soleil deux fois — une fois au sol, puis depuis le 124e étage.",
    "Les Émirats arabes unis n'ont pas d'impôt sur le revenu — c'est une grande raison pour laquelle 88 % de la population est née à l'étranger.",
    "La police de Dubaï roule en Lamborghini, Ferrari et même Bugatti Veyron — toutes en service réel.",
    "Aux Émirats, les démonstrations d'affection en public sont légalement encadrées ; même les couples mariés évitent plus que se tenir la main.",
    "Dubaï reçoit à peine 100 mm de pluie par an — quand il pleut, les routes inondent et les écoles ferment.",
    "Le Palm Jumeirah est visible depuis l'espace et entièrement construit en sable dragué du Golfe.",
    "Le Dubai Mall est le plus grand centre commercial au monde par superficie — il abrite un aquarium de 33 000 créatures marines.",
    "Le chocolat au lait de chamelle est un vrai souvenir de Dubaï — plus sucré que le lait de vache, et entièrement halal.",
    "Le ramadan change le rythme de la ville : la plupart des restaurants ne servent qu'au coucher du soleil, mais les hôtels touristiques offrent souvent un service de jour avec rideaux.",
    "La Grande Mosquée Sheikh Zayed à Abu Dhabi abrite le plus grand tapis tissé main au monde, fait par 1 300 tisserandes en deux ans.",
  ],
  taiwan: [
    "Les marchés nocturnes de Taipei restent ouverts jusqu'à 1-2 h du matin — Shilin est le plus célèbre, avec plus de 500 stands.",
    "Le bubble tea (boba) est né à Taïwan dans les années 1980. Chun Shui Tang à Taichung en revendique l'origine et reste ouvert.",
    "Taipei 101 fut le plus haut bâtiment du monde de 2004 à 2010. À l'intérieur, un amortisseur à masse accordée de 660 tonnes est visible au public.",
    "Taïwan a la forme d'une patate douce — les locaux s'appellent affectueusement « patates douces ».",
    "Le métro de Taipei est célèbre pour sa propreté — manger, boire et même mâcher du chewing-gum sont passibles d'amende.",
    "Au 7-Eleven taïwanais, on fait tout : payer ses factures, retirer des billets, déposer son linge, et même envoyer des cadeaux de mariage.",
    "Le tofu puant a une odeur forte mais un goût étonnamment doux et croustillant. Le berceau, Shenkeng, près de Taipei, vaut le détour.",
    "Taïwan utilise les caractères chinois traditionnels (繁體字), à la différence du continent qui utilise les simplifiés.",
    "Les sources chaudes de Beitou, à 30 minutes de métro du centre de Taipei, perpétuent un rituel d'inspiration japonaise depuis le début du XXe siècle.",
    "Taïwan compte 286 montagnes de plus de 3 000 mètres — l'une des plus fortes densités de hauts sommets au monde.",
  ],
};

const ALL_TRIVIA: Record<Locale, Pool> = {
  en: TRIVIA_EN,
  ko: TRIVIA_KO,
  ja: TRIVIA_JA,
  zh: TRIVIA_ZH,
  fr: TRIVIA_FR,
};

const GENERIC_BY_LOCALE: Record<Locale, string[]> = {
  en: [
    "There are around 195 countries in the world, depending on how you count them.",
    "About 1.4 billion international tourist trips happen every year.",
    "The most-visited city in the world is Bangkok, with over 22 million arrivals annually.",
    "The longest non-stop commercial flight is Singapore to New York — over 18 hours.",
    "About 100,000 commercial flights take off every day worldwide.",
    "The world's largest airport by area is King Fahd International in Saudi Arabia — bigger than Manhattan.",
    "Antarctica is the only continent without a permanent population.",
    "The world's smallest hotel (Eh'häusl in Germany) sleeps two people.",
  ],
  ko: [
    "세계에는 약 195개 나라가 있어요(셈법에 따라 다름).",
    "매년 약 14억 회의 국제 관광 이동이 일어나요.",
    "세계에서 가장 많이 방문되는 도시는 방콕 — 연 2,200만 명 이상이에요.",
    "세계 최장 직항 노선은 싱가포르-뉴욕 — 18시간이 넘어요.",
    "전 세계에서 매일 약 10만 편의 상업 항공편이 이륙해요.",
    "면적 기준 세계 최대 공항은 사우디 킹 파드 국제공항 — 맨해튼보다 커요.",
    "남극은 영구 거주민이 없는 유일한 대륙이에요.",
    "세계에서 가장 작은 호텔(독일 에호이슬)은 단 2명만 머물 수 있어요.",
  ],
  ja: [
    "世界には約195の国があります(数え方による)。",
    "毎年約14億件の国際観光旅行が行われています。",
    "世界で最も訪問される都市はバンコクで、年間2,200万人以上が訪れます。",
    "世界最長の直行便はシンガポール~ニューヨーク — 18時間以上。",
    "世界では毎日約10万便の商用フライトが出発しています。",
    "面積で世界最大の空港はサウジのキング・ファハド国際空港 — マンハッタンより広いです。",
    "南極は定住人口がいない唯一の大陸です。",
    "世界最小のホテル(ドイツのEh'häusl)は2名で泊まれます。",
  ],
  zh: [
    "世界上约有195个国家(取决于如何计算)。",
    "每年约有14亿次国际旅游出行。",
    "世界上访问量最大的城市是曼谷,每年游客超过2,200万。",
    "世界上最长的直达商业航班是新加坡飞纽约 — 超过18小时。",
    "全世界每天约有10万架次商业航班起飞。",
    "按面积计算,世界最大的机场是沙特阿拉伯的法赫德国王国际机场 — 比曼哈顿还大。",
    "南极是唯一没有常住人口的大陆。",
    "世界上最小的酒店(德国Eh'häusl)只能住两个人。",
  ],
  fr: [
    "Il y a environ 195 pays dans le monde, selon la méthode de comptage.",
    "Environ 1,4 milliard de voyages touristiques internationaux ont lieu chaque année.",
    "La ville la plus visitée au monde est Bangkok, avec plus de 22 millions d'arrivées par an.",
    "Le plus long vol commercial sans escale relie Singapour à New York — plus de 18 heures.",
    "Environ 100 000 vols commerciaux décollent chaque jour dans le monde.",
    "Le plus grand aéroport au monde par superficie est King Fahd International en Arabie saoudite — plus grand que Manhattan.",
    "L'Antarctique est le seul continent sans population permanente.",
    "Le plus petit hôtel du monde (Eh'häusl en Allemagne) accueille deux personnes.",
  ],
};

/** Country aliases — map common destination country names to trivia keys. */
const COUNTRY_ALIASES: Record<string, string> = {
  japan: "japan",
  france: "france",
  thailand: "thailand",
  korea: "south-korea",
  "south korea": "south-korea",
  "republic of korea": "south-korea",
  usa: "united-states",
  "united states": "united-states",
  "united states of america": "united-states",
  america: "united-states",
  italy: "italy",
  spain: "spain",
  uk: "united-kingdom",
  "united kingdom": "united-kingdom",
  britain: "united-kingdom",
  england: "united-kingdom",
  germany: "germany",
  deutschland: "germany",
  vietnam: "vietnam",
  indonesia: "indonesia",
  iceland: "iceland",
  peru: "peru",
  uae: "united-arab-emirates",
  "united arab emirates": "united-arab-emirates",
  emirates: "united-arab-emirates",
  taiwan: "taiwan",
  "republic of china": "taiwan",
  // Locale-spelled aliases — Korean / Japanese / Chinese / French names
  // routed back to the canonical English slug so the localized pools
  // still resolve correctly when Claude returns destinationCountry in
  // the user's language.
  일본: "japan",
  日本: "japan",
  日本国: "japan",
  japon: "japan",
  프랑스: "france",
  フランス: "france",
  法国: "france",
  태국: "thailand",
  タイ: "thailand",
  泰国: "thailand",
  thaïlande: "thailand",
  한국: "south-korea",
  대한민국: "south-korea",
  韓国: "south-korea",
  韩国: "south-korea",
  corée: "south-korea",
  미국: "united-states",
  アメリカ: "united-states",
  美国: "united-states",
  "états-unis": "united-states",
  이탈리아: "italy",
  イタリア: "italy",
  意大利: "italy",
  italie: "italy",
  스페인: "spain",
  スペイン: "spain",
  西班牙: "spain",
  espagne: "spain",
  영국: "united-kingdom",
  イギリス: "united-kingdom",
  英国: "united-kingdom",
  "royaume-uni": "united-kingdom",
  독일: "germany",
  ドイツ: "germany",
  德国: "germany",
  allemagne: "germany",
  베트남: "vietnam",
  ベトナム: "vietnam",
  越南: "vietnam",
  인도네시아: "indonesia",
  インドネシア: "indonesia",
  印度尼西亚: "indonesia",
  印尼: "indonesia",
  indonésie: "indonesia",
  아이슬란드: "iceland",
  アイスランド: "iceland",
  冰岛: "iceland",
  islande: "iceland",
  페루: "peru",
  ペルー: "peru",
  秘鲁: "peru",
  pérou: "peru",
  아랍에미리트: "united-arab-emirates",
  "아랍 에미리트": "united-arab-emirates",
  アラブ首長国連邦: "united-arab-emirates",
  アラブ首長国: "united-arab-emirates",
  阿联酋: "united-arab-emirates",
  阿拉伯联合酋长国: "united-arab-emirates",
  "émirats arabes unis": "united-arab-emirates",
  대만: "taiwan",
  타이완: "taiwan",
  台湾: "taiwan",
  taïwan: "taiwan",
};

/** Look up trivia for a destination country in a given locale. Falls back
 *  through: locale-country → locale-generic → en-generic. */
export function getTriviaForCountry(country: string, locale: Locale = "en"): string[] {
  const key = country.toLowerCase().trim();
  const slug = COUNTRY_ALIASES[key] ?? key;
  const localePool = ALL_TRIVIA[locale] ?? ALL_TRIVIA.en;
  return (
    localePool[slug] ??
    GENERIC_BY_LOCALE[locale] ??
    GENERIC_BY_LOCALE.en
  );
}

/** Pick N random distinct trivia entries for a country in a locale. */
export function pickTrivia(
  country: string,
  locale: Locale,
  count: number,
): string[] {
  const pool = getTriviaForCountry(country, locale);
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, pool.length));
}

/**
 * Mulberry32 — small, fast deterministic PRNG. Same seed → same sequence.
 * Used so the trivia order for a given plan is stable across the site
 * render, the PDF render, and every regeneration. Without this, a user
 * sees one fact on the site, a different fact in the PDF, then a third
 * fact on a re-download — confusing and breaks the "this is the same plan"
 * promise.
 */
function mulberry32(seed: number) {
  return function () {
    let t = (seed += 0x6d2b79f5);
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function hashString(s: string): number {
  let h = 0;
  for (let i = 0; i < s.length; i++) {
    h = (Math.imul(31, h) + s.charCodeAt(i)) | 0;
  }
  return h;
}

/**
 * Pick N distinct trivia entries deterministically based on a seed string
 * (e.g. plan UUID). Same seed always returns the same shuffled slice, so
 * the site and the PDF show identical trivia for the same plan.
 */
export function seededPickTrivia(
  country: string,
  locale: Locale,
  count: number,
  seed: string,
): string[] {
  const pool = getTriviaForCountry(country, locale);
  const rng = mulberry32(hashString(seed));
  const arr = [...pool];
  // Fisher-Yates with the seeded RNG.
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr.slice(0, Math.min(count, arr.length));
}
