import type { Locale } from "../../i18n/locales";

export interface DisclaimerSection {
  heading: string;
  body: string;
}

export interface DisclaimerContent {
  metaTitle: string;
  metaDescription: string;
  eyebrow: string;
  headline: string;
  lastUpdated: string;
  sections: DisclaimerSection[];
  contactHeading: string;
  contactPrefix: string;
}

export const DISCLAIMER_CONTENT: Record<Locale, DisclaimerContent> = {
  en: {
    metaTitle: "Disclaimer",
    metaDescription:
      "Disclaimer for gliddy — accuracy of AI-generated trip plans, affiliate relationships, and refund terms.",
    eyebrow: "Legal",
    headline: "Disclaimer",
    lastUpdated: "Last updated: April 17, 2026",
    sections: [
      {
        heading: "General disclaimer",
        body: "gliddy plans are generated by an AI model (Anthropic Claude) from your inputs and a curated place library. They are intended as a thoughtful starting point, not a guaranteed itinerary. Opening hours, prices, and availability change. Always verify critical details (restaurant reservations, entry tickets, transit schedules) before you travel.",
      },
      {
        heading: "Accuracy",
        body: "We work hard to keep the underlying data current, but we cannot guarantee that every place, address, or hour in your plan is up to date at the moment you travel. If you notice something clearly wrong, tell us and we will correct it.",
      },
      {
        heading: "Refund policy",
        body: "If generation fails for technical reasons, we refund you automatically. If you receive a plan but it contains a clearly hallucinated place (a restaurant or attraction that does not exist), reply to your delivery email within 14 days and we will refund you. We do not refund based on taste — liking or disliking a recommendation is subjective.",
      },
      {
        heading: "Not a travel agent",
        body: "We do not book hotels, flights, transit, or tickets for you. We suggest options with links to affiliate partners. You are responsible for all bookings and verifying availability and price.",
      },
      {
        heading: "Affiliate disclosure",
        body: "This site participates in affiliate programs with Agoda, Aviasales, Airalo, and other travel services. We may earn a commission when you click an affiliate link and make a purchase. This comes at no additional cost to you. Our affiliate relationships do not influence plan content.",
      },
      {
        heading: "Limitation of liability",
        body: "In no event shall gliddy be liable for any loss or damage, including without limitation indirect or consequential loss, arising from the use of information on this site or in any plan we generate. Travel decisions are yours alone.",
      },
      {
        heading: "External links",
        body: "This site contains links to external services. We have no control over their content or privacy practices.",
      },
    ],
    contactHeading: "Contact",
    contactPrefix: "If you have concerns about any information in a plan, email",
  },
  ko: {
    metaTitle: "면책 조항",
    metaDescription:
      "gliddy 면책 조항 — AI 생성 여행 플랜의 정확성, 제휴 관계, 환불 조건.",
    eyebrow: "법적 고지",
    headline: "면책 조항",
    lastUpdated: "최종 수정: 2026년 4월 17일",
    sections: [
      {
        heading: "일반 면책 조항",
        body: "gliddy 플랜은 AI 모델(Anthropic Claude)이 회원님의 입력과 큐레이션된 장소 데이터베이스를 바탕으로 생성합니다. 보장된 일정이 아니라 사려 깊은 출발점으로 활용해 주세요. 운영 시간, 가격, 예약 가능 여부는 변동됩니다. 출발 전 핵심 정보(식당 예약, 입장권, 교통편 시간표)는 반드시 직접 확인해 주세요.",
      },
      {
        heading: "정확성",
        body: "기반 데이터를 최신 상태로 유지하기 위해 노력하지만, 회원님 여행 시점에 모든 장소·주소·운영 시간이 최신이라고 보장할 수는 없습니다. 명백히 잘못된 부분을 발견하시면 알려주세요. 수정하겠습니다.",
      },
      {
        heading: "환불 정책",
        body: "기술적 사유로 생성에 실패한 경우 자동 환불해 드립니다. 플랜은 받았지만 명백히 환각된 장소(존재하지 않는 식당이나 관광지)가 포함된 경우, 배송 메일에 14일 이내 회신해 주시면 환불해 드립니다. 취향 차이로는 환불하지 않습니다 — 추천을 좋아하거나 싫어하는 것은 주관적이기 때문입니다.",
      },
      {
        heading: "여행사가 아닙니다",
        body: "호텔, 항공편, 교통, 티켓을 대신 예약하지 않습니다. 옵션을 제안하고 제휴 파트너 링크를 드립니다. 모든 예약과 가격·예약 가능 여부 확인은 회원님 책임입니다.",
      },
      {
        heading: "제휴 관계 고지",
        body: "본 사이트는 Agoda, Aviasales, Airalo 등 여행 서비스의 제휴 프로그램에 참여합니다. 제휴 링크를 통한 구매 시 수수료를 받을 수 있습니다. 회원님께 추가 비용은 없습니다. 제휴 관계가 플랜 내용에 영향을 주지 않습니다.",
      },
      {
        heading: "책임 제한",
        body: "본 사이트의 정보 또는 생성된 플랜 사용으로 인한 어떠한 손실이나 손해(간접적·결과적 손실 포함)에 대해서도 gliddy는 책임지지 않습니다. 여행 결정은 회원님께 있습니다.",
      },
      {
        heading: "외부 링크",
        body: "본 사이트에는 외부 서비스 링크가 포함됩니다. 해당 사이트의 내용이나 개인정보 처리 방식에 대해 책임지지 않습니다.",
      },
    ],
    contactHeading: "문의",
    contactPrefix: "플랜 정보에 대한 문의가 있으시면 다음으로 메일 주세요:",
  },
  ja: {
    metaTitle: "免責事項",
    metaDescription:
      "gliddy 免責事項 — AI生成プランの正確性、アフィリエイト関係、返金条件。",
    eyebrow: "法的事項",
    headline: "免責事項",
    lastUpdated: "最終更新: 2026年4月17日",
    sections: [
      {
        heading: "一般免責事項",
        body: "gliddyのプランはAIモデル(Anthropic Claude)が、お客様の入力情報とキュレーションされた場所データベースをもとに生成しています。保証された旅程ではなく、検討の出発点としてお使いください。営業時間、価格、予約可否は変動します。出発前に重要な情報(レストラン予約、入場券、交通機関の時刻表)は必ずご自身でご確認ください。",
      },
      {
        heading: "正確性",
        body: "基盤データを最新に保つよう努めていますが、お客様の旅行時点ですべての場所・住所・営業時間が最新であることは保証できません。明らかに誤っている点を見つけた場合はお知らせください。修正いたします。",
      },
      {
        heading: "返金ポリシー",
        body: "技術的な理由で生成に失敗した場合、自動的に返金いたします。プランは届いたものの、明らかに架空の場所(存在しないレストランや観光地)が含まれていた場合、配送メールに14日以内にご返信いただければ返金いたします。好みの違いによる返金はいたしません — 推薦を好むか嫌うかは主観的なものだからです。",
      },
      {
        heading: "旅行代理店ではありません",
        body: "ホテル、航空券、交通、チケットの予約代行は行いません。オプションを提案し、アフィリエイトパートナーへのリンクをお渡しします。すべての予約と空き状況・価格の確認はお客様の責任です。",
      },
      {
        heading: "アフィリエイト開示",
        body: "本サイトはAgoda、Aviasales、Airalo等の旅行サービスのアフィリエイトプログラムに参加しています。アフィリエイトリンク経由のご購入で、当方が手数料を受け取る場合があります。お客様に追加費用は発生しません。アフィリエイト関係がプラン内容に影響することはありません。",
      },
      {
        heading: "責任の制限",
        body: "本サイトの情報、または当方が生成したプランの使用に起因する損失または損害(間接的または結果的損失を含む)について、gliddyは一切責任を負いません。旅行に関する決定はお客様自身に委ねられます。",
      },
      {
        heading: "外部リンク",
        body: "本サイトには外部サービスへのリンクが含まれています。それらの内容やプライバシー慣行について、当方には責任がありません。",
      },
    ],
    contactHeading: "お問い合わせ",
    contactPrefix: "プラン情報についてご懸念があれば、次へメールをお送りください:",
  },
  zh: {
    metaTitle: "免责声明",
    metaDescription:
      "gliddy 免责声明 — AI 生成行程的准确性、推广合作关系、退款条款。",
    eyebrow: "法律事项",
    headline: "免责声明",
    lastUpdated: "最后更新: 2026年4月17日",
    sections: [
      {
        heading: "一般免责声明",
        body: "gliddy 行程由 AI 模型(Anthropic Claude)根据您的输入和精选的地点数据库生成。它们是经过深思熟虑的起点,而非保证的行程。营业时间、价格和预订情况会变化。出发前请始终核实关键细节(餐厅预订、入场券、交通时刻表)。",
      },
      {
        heading: "准确性",
        body: "我们努力保持底层数据最新,但无法保证您旅行时计划中的每个地点、地址或营业时间都是最新的。如果您发现明显错误,请告诉我们,我们会修正。",
      },
      {
        heading: "退款政策",
        body: "如因技术原因生成失败,我们会自动退款。如果您收到的行程包含明显虚构的地点(不存在的餐厅或景点),请在 14 天内回复您的发送邮件,我们会退款。我们不基于口味偏好退款 — 喜欢或不喜欢推荐是主观的。",
      },
      {
        heading: "非旅行社",
        body: "我们不为您预订酒店、航班、交通或票务。我们提供选项和推广合作伙伴链接。所有预订及确认空房与价格由您负责。",
      },
      {
        heading: "推广合作披露",
        body: "本站参与 Agoda、Aviasales、Airalo 及其他旅行服务的推广合作计划。当您通过推广链接进行购买时,我们可能获得佣金。这不会对您产生额外费用。我们的合作关系不影响计划内容。",
      },
      {
        heading: "责任限制",
        body: "在任何情况下,gliddy 不对因使用本站信息或我们生成的任何计划而产生的任何损失或损害(包括但不限于间接或后果性损失)承担责任。旅行决策仅由您自己作出。",
      },
      {
        heading: "外部链接",
        body: "本站包含外部服务的链接。我们无法控制其内容或隐私惯例。",
      },
    ],
    contactHeading: "联系我们",
    contactPrefix: "如对计划中的任何信息有疑虑,请发送邮件至",
  },
  fr: {
    metaTitle: "Avertissement",
    metaDescription:
      "Avertissement pour gliddy — précision des plans de voyage générés par IA, relations d'affiliation et conditions de remboursement.",
    eyebrow: "Mentions légales",
    headline: "Avertissement",
    lastUpdated: "Dernière mise à jour : 17 avril 2026",
    sections: [
      {
        heading: "Avertissement général",
        body: "Les plans gliddy sont générés par un modèle d'IA (Anthropic Claude) à partir de vos entrées et d'une bibliothèque de lieux sélectionnés. Ils sont conçus comme un point de départ réfléchi, pas comme un itinéraire garanti. Les horaires d'ouverture, les prix et la disponibilité changent. Vérifiez toujours les détails critiques (réservations de restaurants, billets d'entrée, horaires de transport) avant de voyager.",
      },
      {
        heading: "Précision",
        body: "Nous travaillons dur pour maintenir les données à jour, mais nous ne pouvons garantir que chaque lieu, adresse ou horaire dans votre plan est à jour au moment de votre voyage. Si vous remarquez quelque chose de manifestement incorrect, dites-le-nous et nous le corrigerons.",
      },
      {
        heading: "Politique de remboursement",
        body: "Si la génération échoue pour des raisons techniques, nous vous remboursons automatiquement. Si vous recevez un plan contenant un lieu manifestement halluciné (un restaurant ou une attraction qui n'existe pas), répondez à votre e-mail de livraison dans les 14 jours et nous vous rembourserons. Nous ne remboursons pas en fonction du goût — aimer ou non une recommandation est subjectif.",
      },
      {
        heading: "Pas une agence de voyages",
        body: "Nous ne réservons pas d'hôtels, de vols, de transports ou de billets pour vous. Nous suggérons des options avec des liens vers des partenaires d'affiliation. Vous êtes responsable de toutes les réservations et de la vérification de la disponibilité et du prix.",
      },
      {
        heading: "Divulgation d'affiliation",
        body: "Ce site participe à des programmes d'affiliation avec Agoda, Aviasales, Airalo et d'autres services de voyage. Nous pouvons gagner une commission lorsque vous cliquez sur un lien d'affiliation et effectuez un achat. Cela ne vous coûte rien de plus. Nos relations d'affiliation n'influencent pas le contenu du plan.",
      },
      {
        heading: "Limitation de responsabilité",
        body: "En aucun cas gliddy ne sera responsable de toute perte ou dommage, y compris sans limitation toute perte indirecte ou consécutive, résultant de l'utilisation des informations sur ce site ou dans tout plan que nous générons. Les décisions de voyage vous appartiennent.",
      },
      {
        heading: "Liens externes",
        body: "Ce site contient des liens vers des services externes. Nous n'avons aucun contrôle sur leur contenu ou leurs pratiques de confidentialité.",
      },
    ],
    contactHeading: "Contact",
    contactPrefix: "Si vous avez des préoccupations concernant les informations d'un plan, écrivez à",
  },
};
