import type { Metadata } from "next";
import Header from "../../components/Header";
import Footer from "../../components/Footer";

export const metadata: Metadata = {
  title: "Disclaimer",
  description:
    "Disclaimer for gliddy — accuracy of AI-generated trip plans, affiliate relationships, and refund terms.",
  alternates: { canonical: "https://checkvisamap.com/disclaimer" },
};

export default function Disclaimer() {
  return (
    <div className="min-h-screen flex flex-col bg-[var(--background)]">
      <Header />

      <main className="max-w-3xl mx-auto w-full px-4 sm:px-6 py-16">
        <p className="text-caption uppercase tracking-[0.18em] text-[var(--text-muted)] mb-4">
          Legal
        </p>
        <h1 className="font-display text-display-lg text-[var(--text-primary)] mb-3">
          Disclaimer
        </h1>
        <p className="text-body-sm text-[var(--text-muted)] mb-10">Last updated: April 17, 2026</p>

        <div className="prose prose-lg max-w-none text-[var(--text-secondary)] prose-strong:text-[var(--text-primary)]">
          <h2>General disclaimer</h2>
          <p>
            gliddy plans are generated by an AI model (Anthropic Claude) from your inputs
            and a curated place library. They are intended as a thoughtful starting point, not a
            guaranteed itinerary. Opening hours, prices, and availability change. Always verify
            critical details (restaurant reservations, entry tickets, transit schedules) before you
            travel.
          </p>

          <h2>Accuracy</h2>
          <p>
            We work hard to keep the underlying data current, but we cannot guarantee that every
            place, address, or hour in your plan is up to date at the moment you travel. If you
            notice something clearly wrong, tell us and we will correct it.
          </p>

          <h2>Refund policy</h2>
          <p>
            If generation fails for technical reasons, we refund you automatically. If you receive a
            plan but it contains a clearly hallucinated place (a restaurant or attraction that does
            not exist), reply to your delivery email within 14 days and we will refund you. We do
            not refund based on taste — liking or disliking a recommendation is subjective.
          </p>

          <h2>Not a travel agent</h2>
          <p>
            We do not book hotels, flights, transit, or tickets for you. We suggest options with
            links to affiliate partners. You are responsible for all bookings and verifying
            availability and price.
          </p>

          <h2>Affiliate disclosure</h2>
          <p>
            This site participates in affiliate programs with Agoda, Aviasales, Airalo, and other
            travel services. We may earn a commission when you click an affiliate link and make a
            purchase. <strong>This comes at no additional cost to you.</strong> Our affiliate
            relationships do not influence plan content.
          </p>

          <h2>Limitation of liability</h2>
          <p>
            In no event shall gliddy be liable for any loss or damage, including without
            limitation indirect or consequential loss, arising from the use of information on this
            site or in any plan we generate. Travel decisions are yours alone.
          </p>

          <h2>External links</h2>
          <p>
            This site contains links to external services. We have no control over their content or
            privacy practices.
          </p>

          <h2>Contact</h2>
          <p>
            If you have concerns about any information in a plan, email{" "}
            <a href="mailto:hello@checkvisamap.com">hello@checkvisamap.com</a>.
          </p>
        </div>
      </main>

      <Footer />
    </div>
  );
}
